export type McUsernames<P extends "java" | "bedrock"> = P extends "java"
    ?
          | "jarcokers2"
          | "spankmypickle"
          | "notreadyforlife"
          | "chokeonmypickle"
          | "jorengamer4"
          | "n0rmie"
          | "demonsht"
          | "stanloonaowo"
          | "tayswiftlover420"
    :
          | "*jarcokers2"
          | "*jarcoalt1"
          | "*jarcoalt2"
          | "*jarcoalt3"
          | "*jorengamer4"
          | "*joren4537"
          | "*joren4133"
          | "*joren5801"
          | "*joren2999";
